version: '3.8'

services:

  database:
    image: mysql:latest
    restart: unless-stopped
    container_name: fpdb-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "database"